version: "3"
services:
  net_get:
    container_name: net_get
    build: .
    image: net_get:latest
    ports:
      - 80:80

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  redis:
      container_name: redis
      image: "redis:alpine"
      restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
      stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  worker:
    build:
      context: "."
      args:
        - "FLASK_ENV=${FLASK_ENV:-production}"
    command: celery worker -B -l info -A net_get
    depends_on:
      - "redis"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - ".:/app"
